In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

 # 第一題：抽點系統
老師想做一個抽點系統, 也就是按一個鍵就抽一位同學出來。某班同學有大雄、胖虎、小夫、宜靜、小杉。

請幫老師寫個點名系統。

Hint
interact_manual 用到的函數可以不用有任何參數
np.random.choice 會從一個 list 隨機取一個元素出來


In [2]:
from ipywidgets import interact_manual
def 抽籤():
    student = ['大雄', '胖虎', '小夫', '宜靜', '小杉']#好有年紀的稱號...一錠是老師自己出的XDD
    print(np.random.choice(student))
interact_manual(抽籤)

A Jupyter Widget

<function __main__.抽籤>

# 第二題：變長變短
做一個數值滑桿, 數字變大某個 bar 就變長或變短。
bar = "■"

Hint
需要先寫一個輸入數字會印出對應長度bar的function

In [3]:
from ipywidgets import interact
def bar(n):
    x = n * '■ '
    print(x)
interact(bar ,n =(1,50))

A Jupyter Widget

<function __main__.bar>

# 第三題：考試加權分數
小明今年考大學
依照 [國, 英, 數甲, 數乙, 物, 化, 生, 歷, 地, 公]
他的分數分別是 [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
而他所想申請的大學各系採計的科目權重分別是
{
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
} 

請幫他做出一個互動介面
讓他在選擇科系後可以看到他的加權分數
取到小數點後第一位

範例輸出
範例圖示1範例圖示2

Hint

需要先寫出一個函數 輸入某個科系的名稱後 會告訴你分數是多少
用 numpy array 可以快速的算出加權分數
如何只顯示到小數點第一位可以參考影片 0407 互動範例BMI計算器
可以用 interact

In [4]:
分數 = [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6] 
權重 = {"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]} 


def 加權分數(科系):
    x = np.dot(分數,權重[科系])
    print("你 {} 的加權分數: {:.2f}".format(科系, x))

interact(加權分數,科系 =  [ "土語系","財政系", "金融系", "國貿系",
                            "會計系","法律系", "公行系","應數系","教育系" ])

A Jupyter Widget

<function __main__.加權分數>

# Challenge Challenge魔鬼挑戰題：
（做完可以直接得到一百分）
將上週挑戰題一所要求的函式在10行以內寫出來

 # 挑戰題一：
請定義一個全班高微成績的函式，輸入是一個(3, 30, 3)的array，  
表示3個班級中30位學生的成績(小考，期中考，期末考)  。

目標輸出則是一個(3, 30, 1)的array，表示所有學生的期末成績，
期末成績計算方式如下：

1. 小考20%，期中考35%，期末考45%  
2. 期中考40%，期末考60%。  
擇優作為期末成績
 
Hint
* 可以用雙重for迴圈 分別跑過班級跟人
* 可以先設一個array裝算出來的成績
* 記得要用return 
* 請做個測試，檢驗你的結果，方便同學評分。

Hint
numpy.dot
numpy.where

In [5]:
x = np.random.randint(0,100,(3,30,3))
def 成績擇優(x):
    total = np.zeros((3,30,1))
    m = np.dot(x,[.2,.35,.45])
    n = np.dot(x,[0,.4,.6])
    total = n
    total[np.where(m > n)] = m[np.where(m > n)]
    return total
print(x)
成績擇優(x)

[[[60 68  0]
  [63 71 40]
  [27 66 37]
  [19  6 73]
  [26 30 69]
  [63 95  3]
  [28 24 80]
  [78 64 97]
  [59 33 85]
  [56  3 60]
  [66 10 37]
  [92 31  3]
  [18 70  7]
  [32 35 28]
  [49 68 76]
  [28  0 90]
  [65 48 36]
  [63 97 74]
  [34 70 72]
  [76 79 27]
  [24 66 29]
  [42 59 74]
  [72 86 67]
  [ 2 71 60]
  [ 5  4 19]
  [70 20 44]
  [ 7 63 16]
  [87 23  4]
  [ 9 26 77]
  [61 74 12]]

 [[91 99 65]
  [ 9 71 69]
  [31 62 33]
  [80 49 99]
  [92 83 70]
  [ 1 85 72]
  [85 86 64]
  [11 61 11]
  [ 9 37 26]
  [36 40 38]
  [47 12 83]
  [91 61 17]
  [32 59  1]
  [48 57 54]
  [99 96 66]
  [15 24 66]
  [ 5 30 13]
  [67 23 60]
  [97 92 38]
  [53 66 75]
  [10  3 24]
  [75 37 39]
  [50 69 94]
  [52 82 80]
  [59 59 23]
  [39 95  1]
  [ 1 34 10]
  [96 15 80]
  [61 92 79]
  [43 37 87]]

 [[69 63  2]
  [56 52 48]
  [19 72 77]
  [ 3 86 16]
  [23 61 34]
  [96 42 83]
  [85 57 42]
  [ 0 90 92]
  [76 19  7]
  [56 18 93]
  [23  4 88]
  [16 59 57]
  [20 38 93]
  [86 18  5]
  [76  1 81]
  [28 44 51]
  [70 35

array([[ 35.8 ,  55.45,  48.6 ,  46.2 ,  53.4 ,  47.2 ,  57.6 ,  83.8 ,
         64.2 ,  39.25,  33.35,  30.6 ,  32.2 ,  31.25,  72.8 ,  54.  ,
         46.  ,  83.2 ,  71.2 ,  55.  ,  43.8 ,  68.  ,  74.65,  64.4 ,
         13.  ,  40.8 ,  34.8 ,  27.25,  56.6 ,  43.5 ],
       [ 82.1 ,  69.8 ,  44.6 ,  79.  ,  78.95,  77.2 ,  75.9 ,  31.  ,
         30.4 ,  38.8 ,  54.6 ,  47.2 ,  27.5 ,  55.2 ,  83.1 ,  49.2 ,
         19.8 ,  48.45,  68.7 ,  71.4 ,  15.6 ,  45.5 ,  84.  ,  80.8 ,
         42.8 ,  41.5 ,  19.6 ,  60.45,  84.2 ,  67.  ],
       [ 36.75,  51.  ,  75.  ,  44.  ,  44.8 ,  71.25,  55.85,  91.2 ,
         25.  ,  63.  ,  54.4 ,  57.8 ,  71.  ,  25.75,  52.  ,  48.2 ,
         66.8 ,  66.  ,  45.4 ,  50.4 ,  32.6 ,  41.6 ,  74.  ,  49.8 ,
         49.4 ,  49.3 ,  43.6 ,  41.5 ,  93.4 ,  50.5 ]])